conda-forge/rattler-build-conda-compat

- pixi.lock
- pyproject.toml
- src/rattler_build_conda_compat/loader.py
Adds types for `loader.py` and enables linting.
@nichmor Can you please check whether the types are correct?
> fix: type loader.py

- .github/workflows/build.yml
- .github/workflows/type-check.yml
- pixi.lock
- pixi.toml
- pyproject.toml
- src/rattler_build_conda_compat/conditional_list.py
- src/rattler_build_conda_compat/lint.py
- src/rattler_build_conda_compat/loader.py
- src/rattler_build_conda_compat/recipe_sources.py
- src/rattler_build_conda_compat/render.py
Remove Self type because its not available for python 3.8.
Bumps to 3.10 and adds `typing-extensions`.
Fixes #19
> remove self type

- .github/workflows/tests.yml
- pixi.lock
- pixi.toml
- pyproject.toml
- src/rattler_build_conda_compat/conditional_list.py
- src/rattler_build_conda_compat/recipe_sources.py
- src/rattler_build_conda_compat/render.py
Adds support for python 3.8 and 3.9. Python 3.8 was used somewhere.
> update to allow py38

- pyproject.toml
Use `312` env by default because with zed you cannot select environments from the GUI which means I need something with pytest included.
> feat: change to 3.12 env

- .gitignore
- src/rattler_build_conda_compat/lint.py
- src/rattler_build_conda_compat/loader.py
- src/rattler_build_conda_compat/utils.py
- tests/__snapshots__/test_rattler_loader.ambr
- tests/data/osx_recipe.yaml
- tests/test_rattler_loader.py
This PR aims to add `allow_missing_selector` argument for `RecipeLoader` which will be used by conda-smithy linter to suggest some lints for osx platform. To do this, we need to ignore other selectors ( treat them as true ) so the osx one will be evaluated.
Also, I'm adding `flatten_lists` that will make just a list of values for this case:
```
python:
if: osx
- 3.8
python:
if: unix
- 3.9
```
`So instead of having python: [[3.8], [3.9]]` we will have python: `[3.8, 3.9]`
> feat: allow eval on non existing namespace

- src/rattler_build_conda_compat/render.py
- src/rattler_build_conda_compat/utils.py
- tests/__snapshots__/test_jinja.ambr
- tests/__snapshots__/test_rattler_render.ambr
- tests/conftest.py
- tests/data/mamba_recipe.yaml
- tests/data/rich_recipe.yaml
- tests/test_rattler_render.py
This PR aims to give `Metadata` ability to render recipe using context values.
It will be used by conda-smithy to ask metadata.name() and metadata.version()
> feat: metadata will render recipe with context

- tests/__snapshots__/test_jinja.ambr
- tests/data/context.yaml
- tests/test_jinja.py
This test got lost but it tests that we are evaluating the context in the right order and can use variables that were previously mentioned in the context itself cc @nichmor
> re-add test for context rendering

- src/rattler_build_conda_compat/jinja/jinja.py
> use sandboxed env

- src/rattler_build_conda_compat/render.py
Conda-smithy expects the maintainers under `meta.meta["extra"]["recipe-maintainers"]`.
However, we had them under `meta.meta["recipe"]["extra"]["recipe-maintainers"].
I am not sure, but maybe we should just move the whole recipe under the `meta` key?
> Fix where we put the `extra` metadata

- src/rattler_build_conda_compat/render.py
The issue only appeared during cross compilation when target was different from the build platform.
I encountered the issue when converting a feedstock to rattler at https://github.com/conda-forge/xformers-feedstock/pull/33
Sister PR: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/360
> Fix wrong target/build platform during rendering

- src/rattler_build_conda_compat/jinja/jinja.py
version updates for `noarch` recipes are currently failing because they don't include a target_platform key. 
With this change we just fall back to `linux-64`.
> fix: fallback target platform

- src/rattler_build_conda_compat/lint.py
- src/rattler_build_conda_compat/render.py
Companion to https://github.com/conda-forge/conda-smithy/pull/2244; necessary to rerender rattler recipes on windows.
> consistently set `encoding=utf-8` for opening files

- src/rattler_build_conda_compat/render.py
- tests/__snapshots__/test_rattler_loader.ambr
- tests/__snapshots__/test_rattler_render.ambr
- tests/data/py_recipe.yaml
- tests/data/variants.yaml
- tests/test_rattler_render.py
Fix the variant value comparison to match strings, in order to handle argument mismatch between `used_variant` and `package_variants`. With newer rattler-build versions, the former has actual types, while the latter has strings, so e.g. `13 != "13"` and no variant is matched, resulting in an `IndexError`.  Add a dummy `c_compiler_version` use to the test recipe to reproduce it.
> Fix variant value type mismatch with newer rattler-build

- src/rattler_build_conda_compat/render.py
- tests/test_rattler_render.py
results in excluding all variants if the variant file includes pins on subpackage outputs (common in conda-forge) leading to IndexError because `package_variants` is empty:
```
>               m.config.variant = package_variants[0]
E               IndexError: list index out of range
```
For example, [suitesparse-feedstock](https://github.com/conda-forge/suitesparse-feedstock/pull/104) recently started failing to rerender because of this, since the `used_variant` for most outputs had `libsuitesparseconfig: 7.9.0 ss790_h0795de7`, while all `package_variants` had `libsuitesparseconfig: 7`, leading to excluding all `package_variants`
I don't know if this is a more general issue or indeed a bug in rattler-build that internal state is being included in the 'variant' input to package metadata, …
> don't include subpackages in used variant

- src/rattler_build_conda_compat/loader.py
- tests/data/recipe_requirements.yaml
- tests/test_rattler_loader.py
closes #73  by ensuring `run_exports` and `ignore_run_exports` preserve their dict structure.
This also results in consistent output for the equivalent yaml:
```
run_exports:
- foo
```
and 
```
run_exports:
weak:
- foo
```
both of which return the latter dict.
> handle run_exports, ignore_run_exports dict format in load_all_requirements

- pixi.lock
- pixi.toml
- tests/__snapshots__/test_rattler_render.ambr
a test was [failing](https://github.com/conda-forge/rattler-build-conda-compat-feedstock/pull/48/checks?check_run_id=39690838772) with up-to-date rattler-build, but that didn't turn up here because tests run in a locked env.
Running `pixi update; pixi run snapshot_update` fixes things
> update lock, snapshots

- src/rattler_build_conda_compat/render.py
- tests/test_rattler_render.py
reduced to first scalar, as it would have done before in deduplicating
not original lists, to preserve expected structure of variant dicts
fixes the rerender problem in https://github.com/conda-forge/marimo-feedstock/pull/210#issuecomment-2774112182
I'm not sure why this situation doesn't come up in any conda-smithy tests
> make sure unused variants are scalars

- src/rattler_build_conda_compat/render.py
- tests/test_rattler_render.py
conda-smithy has [started to use meta.dist()](https://github.com/conda-forge/conda-smithy/pull/2300/files#diff-dc66a1980eec62725cfb8b6faea5b3c90dc7d1009d1229f5f55eecfb267a6677R1200), which [fails](https://github.com/conda-forge/conda-forge-webservices/actions/runs/14569433726/job/40863863605#step:5:4700) for many v1 recipes (I think any with a templated build string) with:
```
File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", line 1200, in <lambda>
metas = sorted(metas, key=lambda x: x.dist())
^^^^^^^^
File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/conda_build/metadata.py", line 1822, in dist
return f"{self.name()}-{self.version()}-{self.build_id()}"
^^^^^^^^^^^^^^^
File …
```
> override meta.build_id so meta.dist() works

- pixi.lock
- pyproject.toml
- src/rattler_build_conda_compat/yaml.py
- tests/test_utils.py
conda-build (and therefore conda-smithy) coerces all values in conda_build_config to strings
conda-smithy re-converts booleans back to bools for `.ci_support` variants, so we should do the same
This fixes the inconsistency for v1 recipes in  https://github.com/conda-forge/conda-smithy/issues/2320 where booleans are str during rerender, but bool during build. With this PR, they are always bool. Copies logic from conda-smithy https://github.com/conda-forge/conda-smithy/pull/2314
> coerce boolean strings to boolean values when writing variant yaml

- pixi.lock
- pixi.toml
- pyproject.toml
- src/rattler_build_conda_compat/render.py
- tests/conftest.py
- tests/data/py_abi3.yaml
- tests/test_rattler_render.py
#85 only dealt with one direction of the conversion. We also have to convert True back to 'true' in `get_used_variant` in order to compare with input variants.
More thorough test added, too, explicitly exercising `is_abi3` as a bool.
> make sure to return booleans as strings from render

- src/rattler_build_conda_compat/yaml.py
- tests/test_yaml.py
This PR ensures that the changes made to the YAML parser do not have global side effects.
> fix: ensure yaml changes are not global

- .github/workflows/tests.yml
- pixi.lock
- pixi.toml
- pyproject.toml
- src/rattler_build_conda_compat/conditional_list.py
- src/rattler_build_conda_compat/jinja/jinja.py
- src/rattler_build_conda_compat/lint.py
- src/rattler_build_conda_compat/loader.py
- src/rattler_build_conda_compat/modify_recipe.py
- src/rattler_build_conda_compat/recipe_sources.py
- src/rattler_build_conda_compat/variant_config.py
- src/rattler_build_conda_compat/yaml.py
- tests/conftest.py
- tests/test_recipe_sources.py
- tests/test_yaml.py
- increase required Python from 3.8 to 3.10
- remove redundant python version spec in ruff and mypy config, both of which should get it from project.requires-python by default
- updates Python requirement
- updates pre-commit, other linter packages
- addresses updated lint
> Require Python 3.10
